# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import utils.default_model


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=utils.default_model.random_nick_name, max_length=100, unique=True),
        ),
    ]
