version: '2'

services:

  nginx:
    container_name: nginx
    image: nginx:1.13.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /Users/sean/WebstormProjects/blog/build:/usr/share/nginx/html
    ports:
      - 80:80
    links:
      - api
      - phpmyadmin
    depends_on:
      - api
      - phpmyadmin

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=blog_dev
      - MYSQL_ROOT_PASSWORD=dora1234
      - character-set-server=utf8mb4
      - collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

  api:
    container_name: blog_api
    build:
      context: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8000:8000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    restart: always
    depends_on:
      - mysql
